<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <title>Blog</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body class="p-3 m-0 border-0 bd-example">

    <div class="container-fluid" style="padding-left: 80px;">
        <a class="navbar-brand" href="<?= $this->url('blog_admin') ?>">
            <img src="<?= $this->basePath('img/logo-v1.png') ?>" height="90" alt="Logo" />&nbsp;
        </a>
    </div>
    <!-- Example Code -->

    <nav class="navbar navbar-expand-lg bg-light" style="padding-left: 80px;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">blog_admin</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="<?= $this->url('blog_admin') ?>">Home</a>
                    <a class="nav-link active" aria-current="page"
                        href="<?= $this->url('blog_admin', ['action' => 'add']) ?>">Add</a>
                </div>
            </div>
        </div>
    </nav>

    <!-- End Example Code -->
</body>

</html>
<div class="container">
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; 2005 -
            <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.
        </p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>


</html>