<?= $this->doctype() ?>

<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Blog_KenhGiaiPhap')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile('https://unpkg.com/@popperjs/core@2')
        ?>

    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<style>
    .dropdown:hover>.dropdown-menu {
        display: block;
    }

    .dropdown>.dropdown-toggle:active {
        /*Without this, clicking will make it sticky*/
        pointer-events: none;
    }
</style>

<body>
    <div class="container-fluid" style="padding-left: 190px;">
        <a class="navbar-brand" href="<?= $this->url('blog') ?>">
            <img src="<?= $this->basePath('img/logo-v1.png') ?>" height="90" alt="Logo" />&nbsp;
        </a>
    </div>

    <nav class="navbar navbar-expand-md navbar-dark pt-20 " role="navigation" style="background-color: #2551a1">
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a style="background-color: #2551a1; border: none; padding: 6px 12px 6px 12px;"
                            class="nav-link btn btn-secondary" type="button" aria-haspopup="true" aria-expanded="false"
                            href="<?= $this->url('blog') ?>">TRANG CHỦ<span class="sr-only">(current)</span></a>
                    </li>

                    <li>
                        <div class="dropdown">

                            <a style="background-color: #2551a1; border: none;" class="btn btn-secondary" type="button"
                                id="dropdownMenuButton" href="https://github.dev/vthduongg/blog_administration"
                                aria-haspopup=" true" aria-expanded="false">
                                MÁY TÍNH
                            </a>
                            <div class=" dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 6]) ?>">Phần mềm máy
                                    tính</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 7]) ?>">Game cho máy
                                    tính</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 8]) ?>">Thủ thuật máy
                                    tính</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 9]) ?>">Cài đặt và hệ
                                    điều hành</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 10]) ?>">Tin tức & tư
                                    vấn</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a style="background-color: #2551a1; border: none;" class="btn btn-secondary" type="button"
                                id="dropdownMenuButton" href="https://github.dev/vthduongg/blog_administration"
                                aria-haspopup=" true" aria-expanded="false">
                                ĐIỆN THOẠI
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 11]) ?>">Thủ thuật
                                    Mobile</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 12]) ?>">Game Mobile</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 13]) ?>">Theme, hình
                                    nền</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 14]) ?>">Ứng dụng
                                    mobile</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 15]) ?>">Tư vấn
                                    mobile</a>
                            </div>
                        </div>
                    </li>

                    <li>
                        <div class="dropdown">
                            <a style="background-color: #2551a1; border: none;" class="btn btn-secondary" type="button"
                                id="dropdownMenuButton" href="https://github.dev/vthduongg/blog_administration"
                                aria-haspopup=" true" aria-expanded="false">
                                THỦ THUẬT
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 16]) ?>">Thủ thuật
                                    Email</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 17]) ?>">Thủ thuật về
                                    Office</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 18]) ?>">Thủ thuật
                                    Facebook</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 19]) ?>">Xử
                                    lý ảnh video</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 20]) ?>">Lưu trữ</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 21]) ?>">Internet</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a style="background-color: #2551a1; border: none;" class="btn btn-secondary" type="button"
                                id="dropdownMenuButton" href="https://github.dev/vthduongg/blog_administration"
                                aria-haspopup=" true" aria-expanded="false">
                                CẨM NANG
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 22]) ?>">Kỹ năng
                                    sống</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 23]) ?>">Kỹ năng công
                                    việc</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 25]) ?>">Học tập</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 26]) ?>">Làm đẹp</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 27]) ?>">Du lịch</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 28]) ?>">Quà tặng</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 29]) ?>">Lễ tết</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown">
                            <a style="background-color: #2551a1; border: none;" class="btn btn-secondary" type="button"
                                id="dropdownMenuButton" href="https://github.dev/vthduongg/blog_administration"
                                aria-haspopup=" true" aria-expanded="false">
                                WEB & HỆ THỐNG
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 30]) ?>">Website</a>
                                <a class="dropdown-item"
                                    href="<?= $this->url('blog', ['action' => 'filter', 'id' => 31]) ?>">Hệ thống</a>
                            </div>
                        </div>
                    </li>

                    <li class="">
                        <div class="input-group rounded" style="padding-left: 70px">
                            <input type="search" style="width: 220px;" class="form-control rounded" placeholder="Search"
                                aria-label="Search" aria-describedby="search-addon" />
                            <span class="input-group-text border-0" id="search-addon">
                                <i class="bi bi-search"></i>
                            </span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container" style="padding-top: 10px">
        <?= $this->content ?>
        <hr>

        <footer>
            <p>&copy; 2005 -
                <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.
            </p>
        </footer>
    </div>

    <?= $this->inlineScript() ?>
</body>

</html>